language: c
sudo: required
services:
  - docker
env:
  global:
    - OCAML_VERSION=4.05
    - BUILD_ID=$(date +%s)
#addons:
#  apt:
#    updated: true
before_install:
  - source scripts/env.sh
#install:
#  - wget https://raw.githubusercontent.com/ocaml/ocaml-ci-scripts/master/.travis-ocaml.sh
#  - bash -ex .travis-ocaml.sh
#  - make depends
#  - export PATH=/home/travis/.opam/4.06.1/bin:$PATH
script:
  - docker pull nickrobison/mirage-virtio:3.0.8
  - docker run --rm -v "${PWD}:/home/opam/mirage" -w /home/opam/mirage -e BUILD_ID nickrobison/mirage-virtio:3.0.8 make build
before_deploy:
  - openssl aes-256-cbc -K $encrypted_e48455ed36d7_key -iv $encrypted_e48455ed36d7_iv -in client-secret.json.enc -out client-secret.json -d
  - bash -ex scripts/init_gcloud.sh

deploy:
  skip_cleanup: true
  provider: script
  script: make deploy
