jobs:
  - job: Build
    pool:
      vmImage: 'ubuntu-latest'
    variables:
      OPAM_CACHE_FOLDER: /home/vsts/.opam
    steps:
      - task: CacheBeta@0
        inputs:
          key: opam | $(Agent.OS)
          path: $(OPAM_CACHE_FOLDER)
          displayName: Cache Opam installation
      - task: DownloadSecureFile@1
        name: secrets
        displayName: 'Download Secrets'
        inputs:
          secureFile: 'secrets.tar.gz'
      - script: |
          echo Unzipping $(secrets.secureFilePath)
          tar -xvf $(secrets.secureFilePath)
      - script: env AGENT_OS=Linux TEST_DISTRIB=yes scripts/azure-install-ocaml.sh
        displayName: Install Ocaml
      - script: |
          echo $PWD
          ls -lah .
      - script: make depends
        displayName: Install Main Dependencies
      - script: |
          pushd /home/vsts/.opam
          echo $PWD
          ls -lah .
          opam update -vv && opam upgrade -y && opam clean
          popd
      - script: make build
        displayName: Build website
  - job: Package
    dependsOn: Build
    pool:
      vmImage: "ubuntu-latest"
    steps:
      - script: docker pull nickrobison/mirage-virtio:3.5.2
        displayName: Download Docker image
      - script: docker run --rm -v "${PWD}:/home/opam/mirage" -w /home/opam/mirage -e BUILD_ID nickrobison/mirage-virtio:3.5.2 scripts/bundle.sh
        displayName: Package
  - deployment: Deploy
    pool:
      vmImage: 'ubuntu-latest'
    dependsOn: Package
    environment: "Google Cloud"
    strategy:
      runOnce:
        deploy:
          steps:
            - script: make deploy



