jobs:
  - job: Linux
    pool:
      vmImage: 'ubuntu-latest'
    steps:
      - task: DownloadSecureFile@1
        name: secrets
        displayName: 'Download Secrets'
        inputs:
          secureFile: 'secrets.tar.gz'
      - script: |
          echo Unzipping $(secrets.secureFilePath)
          tar -zvf $(secrets.secureFilePath)
      - script: env AGENT_OS=Linux TEST_DISTRIB=yes scripts/azure-install-ocaml.sh
        displayName: Install Ocaml
      - script: make depends
        displayName: Install Main Dependencies
      - script: opam update && opam upgrade -y
        displayName: Update opam
      - script: make build
        displayName: Build website
